// Code generated by MockGen. DO NOT EDIT.
// Source: reward.go
//
// Generated by this command:
//
//	mockgen -source=reward.go -destination=../../mocks/accrual/reward_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/prbllm/go-loyalty-service/internal/accrual/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRewardService is a mock of RewardService interface.
type MockRewardService struct {
	ctrl     *gomock.Controller
	recorder *MockRewardServiceMockRecorder
	isgomock struct{}
}

// MockRewardServiceMockRecorder is the mock recorder for MockRewardService.
type MockRewardServiceMockRecorder struct {
	mock *MockRewardService
}

// NewMockRewardService creates a new mock instance.
func NewMockRewardService(ctrl *gomock.Controller) *MockRewardService {
	mock := &MockRewardService{ctrl: ctrl}
	mock.recorder = &MockRewardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardService) EXPECT() *MockRewardServiceMockRecorder {
	return m.recorder
}

// RegisterReward mocks base method.
func (m *MockRewardService) RegisterReward(ctx context.Context, reward model.RewardRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterReward", ctx, reward)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterReward indicates an expected call of RegisterReward.
func (mr *MockRewardServiceMockRecorder) RegisterReward(ctx, reward any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterReward", reflect.TypeOf((*MockRewardService)(nil).RegisterReward), ctx, reward)
}
