// Code generated by MockGen. DO NOT EDIT.
// Source: reward.go
//
// Generated by this command:
//
//	mockgen -source=reward.go -destination=../../mocks/accrual/reward_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/prbllm/go-loyalty-service/internal/accrual/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRewardRepository is a mock of RewardRepository interface.
type MockRewardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRewardRepositoryMockRecorder
	isgomock struct{}
}

// MockRewardRepositoryMockRecorder is the mock recorder for MockRewardRepository.
type MockRewardRepositoryMockRecorder struct {
	mock *MockRewardRepository
}

// NewMockRewardRepository creates a new mock instance.
func NewMockRewardRepository(ctrl *gomock.Controller) *MockRewardRepository {
	mock := &MockRewardRepository{ctrl: ctrl}
	mock.recorder = &MockRewardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardRepository) EXPECT() *MockRewardRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRewardRepository) Create(ctx context.Context, rule model.RewardRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRewardRepositoryMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRewardRepository)(nil).Create), ctx, rule)
}

// ExistsByMatch mocks base method.
func (m *MockRewardRepository) ExistsByMatch(ctx context.Context, match string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByMatch", ctx, match)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByMatch indicates an expected call of ExistsByMatch.
func (mr *MockRewardRepositoryMockRecorder) ExistsByMatch(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByMatch", reflect.TypeOf((*MockRewardRepository)(nil).ExistsByMatch), ctx, match)
}

// GetAll mocks base method.
func (m *MockRewardRepository) GetAll(ctx context.Context) ([]model.RewardRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.RewardRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRewardRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRewardRepository)(nil).GetAll), ctx)
}
