// Code generated by MockGen. DO NOT EDIT.
// Source: internal/accrual/service/reward.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/prbllm/go-loyalty-service/internal/accrual/model"
)

// MockRewardService is a mock of RewardService interface.
type MockRewardService struct {
	ctrl     *gomock.Controller
	recorder *MockRewardServiceMockRecorder
}

// MockRewardServiceMockRecorder is the mock recorder for MockRewardService.
type MockRewardServiceMockRecorder struct {
	mock *MockRewardService
}

// NewMockRewardService creates a new mock instance.
func NewMockRewardService(ctrl *gomock.Controller) *MockRewardService {
	mock := &MockRewardService{ctrl: ctrl}
	mock.recorder = &MockRewardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardService) EXPECT() *MockRewardServiceMockRecorder {
	return m.recorder
}

// RegisterReward mocks base method.
func (m *MockRewardService) RegisterReward(ctx context.Context, match string, reward int64, rewardType model.RewardType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterReward", ctx, match, reward, rewardType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterReward indicates an expected call of RegisterReward.
func (mr *MockRewardServiceMockRecorder) RegisterReward(ctx, match, reward, rewardType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterReward", reflect.TypeOf((*MockRewardService)(nil).RegisterReward), ctx, match, reward, rewardType)
}
